CREATE TABLE IF NOT EXISTS public.product_category (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    description character varying(500),
    product_type_id integer NOT NULL,
    order_id integer
) INHERITS (public.control_fields);

ALTER TABLE public.product_category
    ADD CONSTRAINT product_category_pkey PRIMARY KEY (id);

ALTER TABLE public.product_category
    ADD CONSTRAINT product_category_product_type_id_fkey
        FOREIGN KEY (product_type_id) REFERENCES public.product_type(id);

CREATE UNIQUE INDEX IF NOT EXISTS product_category_product_type_name_unique_idx
    ON public.product_category (product_type_id, lower((name)::text));

CREATE INDEX IF NOT EXISTS product_category_product_type_active_order_idx
    ON public.product_category (product_type_id, active, order_id);

ALTER TABLE public.product
    ADD COLUMN IF NOT EXISTS product_category_id integer;

ALTER TABLE public.product
    ADD CONSTRAINT product_product_category_id_fkey
        FOREIGN KEY (product_category_id) REFERENCES public.product_category(id);

INSERT INTO public.product_type (name, active)
SELECT 'ACCESORIO', true
WHERE NOT EXISTS (
    SELECT 1
    FROM public.product_type
    WHERE lower(name) = 'accesorio'
);
